# Based on: https://pnpm.io/using-changesets#add-the-workflow

name: Changesets

on:
  push:
    branches:
      - main

env:
  CI: true

permissions:

jobs:
  version:
    timeout-minutes: 15
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Use pnpm ${{ vars.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ vars.PNPM_VERSION }}

      - name: Use Node.js ${{ vars.NODE_VERSION}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'pnpm'
      
      - name: Install Node.js dependencies
        run: pnpm install

      - name: Install WASM-Pack
        run: cargo install wasm-pack

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test
      
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1

      - name: Publish to npm
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: pnpm changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
